[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'aharisu/vim_goshrepl'
build = 'make'

[[plugins]]
repo = 'aharisu/vim-gdev'

[[plugins]]
repo = 'Shougo/neocomplcache'

[[plugins]]
repo = 'amdt/vim-niji'
